import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import CustomCursor from "./components/effects/CustomCursor";

const instrumentSans = Instrument_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-instrument-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en"
      className={`${instrumentSans.variable} antialiased`}
      >
      <body
        className={`${instrumentSans.variable} antialiased`}
        >
        <Navbar/>
        <CustomCursor/>
        {children}
      </body>
    </html>
  );
}

